
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Define actual URLs and keys directly for development
const SUPABASE_URL = 'https://prcneielcpgqwzayekbc.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InByY25laWVsY3BncXd6YXlla2JjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU2NDc4NzEsImV4cCI6MjA2MTIyMzg3MX0.bken5OWzWU6AHycYkOSBUqc0QZB4XrV4yCACpDxO0OI';

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL,
  SUPABASE_ANON_KEY,
  {
    auth: {
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true
    }
  }
);

// Add debug flag to help with troubleshooting
if (import.meta.env.DEV) {
  console.log('Supabase client initialized with URL:', SUPABASE_URL);
  
  // Check for existing session on init
  supabase.auth.getSession().then(({ data }) => {
    if (data.session) {
      console.log('Existing session found at initialization');
    } else {
      console.log('No session found at initialization');
    }
  });
}
